# Generated by Django 3.1.1 on 2020-10-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_appversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='sunset_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
