# Generated by Django 3.1.1 on 2020-09-15 05:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_license_mailinglistsubscriber_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='issued_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='license',
            name='key',
            field=models.CharField(blank=True, help_text='Leave blank to generate.', max_length=36, null=True),
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17)),
                ('activation_date', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.license')),
            ],
        ),
    ]
